istiod:
  global:
    istioNamespace: istio-system

gateway:
  fullnameOverride: istio-ingress
  global:
    istioNamespace: istio-system
  service:
    type: NodePort
  autoscaling:
    enabled: false

base: {}
