istiod:
  global:
    istioNamespace: istio-system
  nodeSelector:
    kubernetes.io/arch: amd64

gateway:
  name: istio-ingress
  global:
    istioNamespace: istio-system
  service:
    type: NodePort
  autoscaling:
    enabled: false
  nodeSelector:
    kubernetes.io/arch: amd64

base: {}
