apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetrygen
  namespace: otel-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetrygen
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      containers:
        - name: telemetrygen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - "traces"
            - "--otlp-endpoint"
            - "otel-collector.opentelemetry-collector.svc.cluster.local:4317"
            - "--otlp-insecure"
            - "--rate"
            - "5"
            - "--duration"
            - "inf"
            - "--service"
            - "demo-telemetrygen"
