apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: k3s-tunnel
    credentials-file: /etc/cloudflared/creds.json

    ingress:
      - hostname: local.cmoreira.dev
        service: http://istio-ingress.istio-system.svc.cluster.local:80
      - hostname: argocd.cmoreira.dev
        service: http://istio-ingress.istio-system.svc.cluster.local:80
      - service: http_status:404
